add idea for autogenerated docs
oven-sh/bun-types pull request #2
Opened 2022-07-27 06:30 UTC by valgaze

Proof of concept for auto-gen'd docs in markdown, demo **[here: ](https://github.com/valgaze/bun-types/blob/autodocs_idea/api-docs/modules.md#bun-types)**

- [ ] ```npm run docs``` to generate types then generate docs based on types in directory **[api-docs](https://github.com/valgaze/bun-types/tree/autodocs_idea/api-docs)**

- [ ] Uses **[typedoc](https://typedoc.org)** to focus on high-value docs rather than manually annotate types

- [ ] (not sure) optional "images" folder to link gifs/assets to repo itself

2022-07-27 07:00 UTC, xHyroM requested changes
Why `npm:` scripts?

2022-07-27 07:01 UTC, valgaze commented
@xHyroM Fun for benchmark

2022-07-27 07:02 UTC, xHyroM commented
Probably remove it, we don't need to have benchmark for generating docs

2022-07-27 07:15 UTC, xHyroM commented
Why api-docs folder is in .gitignore?
![image](https://user-images.githubusercontent.com/56601352/181185135-9a22e406-bcc8-442e-8919-e4b72df01b1b.png)

2022-07-27 08:05 UTC, valgaze commented
@xHyroM wasn't sure whether many files would make noisy source control-- I'll add to this PR

2022-07-27 08:14 UTC, xHyroM commented
resolve conflicts

2022-07-27 08:27 UTC, Jarred-Sumner commented
This is nice. Can we put all of them into a single file and into the readme of this repository below "Contributing"? The goal is so you can CMD + F easily to search all of bun's types at once

2022-07-27 09:45 UTC, valgaze commented
@xHyroM -- deconflicted

@Jarred-Sumner -- There's too much data for a renderable README-- using **[concat-md](https://www.npmjs.com/package/concat-md)** I was getting ~6mb's and it'll probably grow over time right?

ex. 
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/1396559/181214227-dc002851-56de-4496-83d8-caaa70f85c3d.png">


W/ this Typedoc appraoch, maybe a compromise would be to concat the **[module.md](https://github.com/valgaze/bun-types/blob/autodocs_example/api-docs/modules.md#bun-types)** that gets generated. That way you could have a renderable readme and still get the CTRL-f search'y experience

ex. https://gist.github.com/valgaze/04dde2c997c016e0640256afb616b23d

To pull off you could do something like the following:

-  **README_top.md**: Top "static" template the README, 

- Concat README.top w/ 
- 
```json
{
    "special_script": "bun run docs && cp README_top.md README.md && cat api-docs/modules.md >> README.md"
}
```

2022-07-27 10:10 UTC, xHyroM commented
Or we can turn on GitHub pages with Jekyll theme (for now)

2022-07-28 15:40 UTC, paperdave commented
![image](https://user-images.githubusercontent.com/24465214/181579764-c9a20e0a-9046-48f6-9acb-55f283fed72f.png)

is this intentional that it points to the bundled types as well as the source?

2022-08-02 12:50 UTC, xHyroM commented
+ can you resolve conflicts?

2022-08-06 00:20 UTC, valgaze commented
@xHyroM deconflicted

2022-08-06 03:54 UTC, xHyroM commented
Can you exclude dist/types.d.ts ?

> @xHyroM deconflicted

2022-08-07 16:09 UTC, xHyroM approved these changes

2022-08-07 16:11 UTC, xHyroM commented
After removing https://github.com/valgaze/bun-types/blob/3f77af99bef82d463fe7b847fb3448134748c6a3/package.json#L21 , ping me and I'll merge this

2022-08-07 16:11 UTC, xHyroM commented
@valgaze

2022-08-07 17:07 UTC, valgaze commented
@xHyroM Alright sorted-- once merged the publicPath url's in the docs should resolve properly

2022-08-07 17:57 UTC, xHyroM commented
Okay, thanks

2022-08-07 18:52 UTC, merged